# permissions to do viewer customdomains.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: customdomain-viewer-role
rules:
- apiGroups:
  - domain.skygear.io
  resources:
  - customdomains
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - domain.skygear.io
  resources:
  - customdomains/status
  verbs:
  - get
