# permissions to do edit customdomainregistrations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: customdomainregistration-editor-role
rules:
- apiGroups:
  - domain.skygear.io
  resources:
  - customdomainregistrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - domain.skygear.io
  resources:
  - customdomainregistrations/status
  verbs:
  - get
  - patch
  - update
