# permissions to do viewer customdomainregistrations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: customdomainregistration-viewer-role
rules:
- apiGroups:
  - domain.skygear.io
  resources:
  - customdomainregistrations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - domain.skygear.io
  resources:
  - customdomainregistrations/status
  verbs:
  - get
