# permissions to do edit customdomains.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: customdomain-editor-role
rules:
- apiGroups:
  - domain.skygear.io
  resources:
  - customdomains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - domain.skygear.io
  resources:
  - customdomains/status
  verbs:
  - get
  - patch
  - update
